require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Firebase Configuration
$RNFirebaseAsStaticFramework = true
use_frameworks! :linkage => :static

# Firebase pods
pod 'FirebaseCore', '~> 10.0'
pod 'FirebaseAuth', '~> 10.0'
pod 'FirebaseMessaging', '~> 10.0'

target 'MyNewApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
        :flipper_configuration => FlipperConfiguration.disabled # Add this if not using Flipper

  )

  post_install do |installer|
    # React Native post-install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Additional settings for Firebase compatibility
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable BUILD_LIBRARY_FOR_DISTRIBUTION for all pods
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
        # Enable modules
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      end
    end
  end
end